# Generated by Django 4.2.7 on 2025-12-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_emailverification_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DELETE FROM tickets_emailverification
            WHERE id NOT IN (
                SELECT sub.id
                FROM (
                    SELECT MAX(id) AS id
                    FROM tickets_emailverification
                    GROUP BY user_id
                ) sub
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
