# Generated by Django 4.2.7 on 2025-12-23 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_duplicate_email_verifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
